name: Secrets and env variables
on:
  workflow_dispatch

jobs:
  learn-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Read a variable
        run: echo "MY_APP is ${{ vars.APP_NAME }}"

      - name: Access the secret
        run: echo "The org level MY_PASS is ${{ secrets.MY_PASS }}"

      - name: Test variable
        env:
          super_secret: ${{ secrets.MY_PASS }}
        run: echo "The org level MY_PASS is $super_secret"

  environment-secrets:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Read env variable
        run: echo "My app name is ${{ vars.APP_NAME }}"
